CREATE DATABASE QLBANHANG
USE QLBANHANG

--1. Tạo và nhập dữ liệu cho các quan hệ trên.
--2. Khai báo các khóa chính và khóa ngoại của quan hệ.
CREATE TABLE NHANVIEN
(
    MANV char(4) CONSTRAINT PK_NV PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	SODT varchar(20),
	NGDK smalldatetime
)

CREATE TABLE SANPHAM
(
    MASP char(4) CONSTRAINT PK_SP PRIMARY KEY,
	NGHD smalldatetime,
	TENSP varchar(20),
	GIA money
)

CREATE TABLE HOADON
(
    MAHD char(4) CONSTRAINT PK_HD PRIMARY KEY,
	MANV char(4),
	TRIGIA money
)

CREATE TABLE CTHD
(
    MAHD char(4),
	MASP char(4),
	SL int
	CONSTRAINT PK_CTHD PRIMARY KEY(MAHD,MASP)
)

--khóa ngoại
SET DATEFORMAT dmy
ALTER TABLE HOADON ADD CONSTRAINT FK_HD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE CTHD ADD CONSTRAINT FK01_CTHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE CTHD ADD CONSTRAINT FK02_CTHD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

--INSERT DỮ LIỆU
/*insert NHANVIEN*/
INSERT INTO NHANVIEN VALUES ('NV01 ','Nguyen Thi ','A ','0123456789','5/1/2020')	
INSERT INTO NHANVIEN VALUES ('NV02 ','Tran ','B ','0987654321','10/5/2020')	

/*insert SANPHAM*/
INSERT INTO SANPHAM VALUES ('SP01 ','Ca chua ',10000)	
INSERT INTO SANPHAM VALUES ('SP02 ','Khoai tay ',15000)	
INSERT INTO SANPHAM VALUES ('SP03 ','Thit heo ',150000)	

/*insert HOADON*/
INSERT INTO HOADON VALUES ('HD01','1/12/2020','NV01',225000)	
INSERT INTO HOADON VALUES ('HD02','2/11/2020','NV02',3425000)	

/*insert CTHD*/
INSERT INTO CTHD VALUES ('HD01 ','SP03',1.5)	
INSERT INTO CTHD VALUES ('HD02 ','SP01',2)	
INSERT INTO CTHD VALUES ('HD02 ','SP02',1.5)	
INSERT INTO CTHD VALUES ('HD02 ','SP03',2)	

--3. Nhân viên chỉ được phép tạo hóa đơn sau khi đã chính thức làm việc.
/*HOADON*/
GO
CREATE TRIGGER TRG_INSERT_UPDATE_HOADON ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @NGHD SMALLDATETIME, @NGDK SMALLDATETIME, @MANV CHAR(4)
	SELECT @MANV = MANV ,@NGHD = NGHD
	FROM inserted

	SELECT @NGDK = NGDK
	FROM NHANVIEN
	WHERE MANV = @MANV

	IF(@NGHD < @NGDK)
	BEGIN
	    PRINT 'ERROR'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
	    PRINT 'THANH CONG'
	END
END

/*NHANVIEN*/
GO
CREATE TRIGGER TRG_UPDATE_NHANVIEN ON NHANVIEN
FOR UPDATE
AS
BEGIN
    DECLARE @NGDK SMALLDATETIME, @MANV CHAR(4), @SOLUONG INT
	SELECT @MANV = MANV, @NGDK = NGDK
	FROM inserted

	SET @SOLUONG=COUNT(*)
	SELECT COUNT(*)
	FROM HOADON
	WHERE MANV = @MANV AND NGHD < @NGDK

	IF(@SOLUONG >=1)
	BEGIN
	    PRINT 'ERROR'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
	    PRINT 'THANH CONG'
	END
END

--4. Cập nhật họ của nhân viên “NV02” thành “Tran Van”.
UPDATE NHANVIEN
SET HO='Tran Van'
WHERE MANV='NV02'

--5. In ra thông tin các nhân viên (MANV, HOTEN, SDT) có lập hóa đơn trong tháng 9/2020.
SELECT NV.MANV, HO,TEN,SODT
FROM NHANVIEN NV, HOADON HD
WHERE NV.MANV=HD.MANV AND YEAR(NGHD)=2020 AND MONTH(NGHD)=9

--6. In ra các hóa đơn (MAHD) đã mua sản phẩm có mã là “SP03” sắp xếp theo số lượng sản phẩm bán ra.
SELECT HD.MAHD
FROM HOADON HD, CTHD
WHERE HD.MAHD=CTHD.MAHD AND MASP='SP03'
ORDER BY SL DESC

--7. In ra các (MASP, TENSP, THANG) đã được mua theo từng tháng trong năm 2020.
SELECT SP.MASP,SP.TENSP,MONTH(NGHD) AS 'THANG'
FROM SANPHAM SP, HOADON HD,CTHD
WHERE SP.MASP=CTHD.MASP AND CTHD.MAHD=HD.MAHD AND YEAR(NGHD)=2020
GROUP BY SP.MASP,SP.TENSP,MONTH(NGHD)

--8. In ra số lượng các hóa đơn có giá trị trên 500,000 đồng và số lượng hóa đơn có giá trị dưới 500,000 đồng (SL_TREN, SL_DUOI).
SELECT *
FROM (SELECT COUNT(MAHD) 'SL_TREN'
      FROM HOADON
	  WHERE TRIGIA>500000) as a,(SELECT COUNT(MAHD) 'SL_duoi'
                                 FROM HOADON
	                             WHERE TRIGIA<500000) as b
      
